# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css, https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css]

  javascripts:    [https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js, https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js]

  has_layout:     true
  layout:         layout
