<?php

    /**
     * Skeleton subclass for performing query and update operations on the 'bc_bicycles' table.
     *
     *
     *
     * This class was autogenerated by Propel 1.4.2 on:
     *
     * 04/18/15 20:24:50
     *
     * You should add additional methods to this class to meet the
     * application requirements.  This class will only be generated as
     * long as it does not already exist in the output directory.
     *
     * @package    lib.model
     */
    class BcBicyclesPeer extends BaseBcBicyclesPeer
    {
        public static function AddSortCriteria($curSort, &$criteria)
        {
            if ($curSort == "asc")
            {
                $criteria->addAscendingOrderByColumn(self::NAME);
            } else
            {
                $criteria->addDescendingOrderByColumn(self::NAME);
            }
        }
        
        public static function AddSearchCriteria($SearchQuery, &$criteria)
        {
            $query = '%' . $SearchQuery . '%';
        
            $name = $criteria->getNewCriterion(BcBicyclesPeer::NAME, $query, Criteria::LIKE);
            $year = $criteria->getNewCriterion(BcBicyclesPeer::YEAR, $query, Criteria::LIKE);
            $frame = $criteria->getNewCriterion(BcBicyclesPeer::FRAME, $query, Criteria::LIKE);
            $speeds = $criteria->getNewCriterion(BcBicyclesPeer::SPEEDS, $query, Criteria::LIKE);
            $brakes = $criteria->getNewCriterion(BcBicyclesPeer::BRAKES, $query, Criteria::LIKE);
            $application = $criteria->getNewCriterion(BcBicyclesPeer::APPLICATION, $query, Criteria::LIKE);
            
            $criteria->add($application->addOr($brakes)->addOr($speeds)->addOr($frame)->addOr($year)->addOr($name));
        }
        
        public static function GetSortParam($curSort)
        {
            $sortParam = "";
            if ($curSort == "asc")
            {
                $sortParam = "&sort=" . $curSort;
            }
            return $sortParam;
        }
    } // BcBicyclesPeer
