<?php


/**
 * Skeleton subclass for performing query and update operations on the 'bc_bicycles' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/18/15 20:24:50
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BcBicyclesPeer extends BaseBcBicyclesPeer 
{
    static public function getSortedBicycles($sort)
    {
        $criteria = new Criteria();
        if ($sort == "asc")
        {
            $criteria->addAscendingOrderByColumn(self::NAME);
        }
        else
        {
            $criteria->addDescendingOrderByColumn(self::NAME);
        }
        
        return self::doSelect($criteria);
    }
} // BcBicyclesPeer
