<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/04/16 23:19:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bicycle',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
